services:
  - name: socii-prod-db-backup
    type: cron
    schedule: "0 3 * * *"
    region: virginia
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socii-prod-db
          property: connectionString

      - key: AWS_REGION
        value: us-east-1

      - key: S3_BUCKET_NAME
        value: socii-prod-postgres-backups

      - key: POSTGRES_VERSION
        value: "18"

      - key: ALPINE_VERSION
        value: "3.23"

      - key: AWS_ROLE_ARN
        sync: false
